### ISSUE TITLE
Command line execution?

### ISSUE THREAD

**Issue by rpodcast** [rikai/audio-visualizer-python#2]
I have an audio-only podcast with occasional screencasts and would like to use this plugin to emulate your approach for User Error.  It works on my laptop but I wondered if there is a way to run it in a batch mode or command line way without the GUI?  I have a beefy headless server that could potentially encode it faster plus it would free up my laptop for other tasks.

**Comment by rikai** [comment]
Sorry for the late response. Did not see this until now. Unfortunately there is not, you may want to open a feature request on the [upstream project](https://github.com/djfun/audio-visualizer-python) for this. 👍

**Comment by rpodcast** [comment]
No problem!  An [issue](https://github.com/djfun/audio-visualizer-python/issues/10) was filed last year in the upstream project and I've added my "me too" for the request.  Hopefully it gets some traction.  I'm assuming you aren't aware of other projects that do a similar thing yet right?
